import type { Metadata, Viewport } from "next";
import "./globals.css";
import ReduxProvider from "./provider";
import ToastModal from "../components/alertModal/toastModal";
import UnderBar from "@/components/underBar";
import TransitionWrapper from "./transitionWrapper";

export const metadata: Metadata = {
  title: "SSDAM",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#000000",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-full min-h-screen">
      <body className="w-full min-h-screen bg-white">
        <ToastModal />
        <TransitionWrapper>
          <ReduxProvider>
            <main className="min-h-screen flex flex-col">{children}</main>
          </ReduxProvider>
        </TransitionWrapper>
        <UnderBar />
      </body>
    </html>
  );
}
