#!/bin/sh

# 커밋 메시지 파일 경로
commit_msg_file=$1

# 커밋 메시지 읽기
commit_msg=$(cat "$commit_msg_file")

# 허용되는 prefix 목록
allowed_prefixes="feat fix docs style refactor test chore hotfix wip"

# prefix 검사
is_valid=false
prefix_found=""
for prefix in $allowed_prefixes; do
  if [[ "$commit_msg" == "$prefix : "* ]]; then
    is_valid=true
    prefix_found=$prefix
    break
  fi
done

# 유효하지 않은 prefix인 경우 커밋 거부
if ! $is_valid; then
  echo "Error: 커밋 메시지 prefix가 유효하지 않습니다."
  echo "허용되는 prefix: $allowed_prefixes"
  echo "prefix 후에 띄어쓰기를 해주세요."
  exit 1
fi

# 현재 브랜치 이름 가져오기
branch_name=$(git symbolic-ref --short HEAD)

# 브랜치 이름에서 이슈 번호 추출
issue_number=$(echo "$branch_name" | grep -oE 'S12P21A106-[0-9]+')

# 커밋 메시지에 이미 이슈 번호가 있는지 확인
if [[ "$commit_msg" =~ \#S12P21A106-[0-9]+ ]]; then
  has_issue=true
else
  has_issue=false
fi

# 이모지가 이미 있는지 확인
if [[ "$commit_msg" =~ ^[[:space:]]*[[:punct:]].*$ ]]; then
  has_emoji=true
else
  has_emoji=false
fi

# 이모지 매핑
case $prefix_found in
  "feat") emoji="✨";;
  "fix") emoji="🐛";;
  "docs") emoji="📝";;
  "style") emoji="🎨";;
  "refactor") emoji="♻️";;
  "test") emoji="☑️";;
  "chore") emoji="⚙️";;
  "hotfix") emoji="👺";;
  "wip") emoji="🚧";;
esac

# 최종 메시지
new_commit_msg="$commit_msg"

# 이모지가 없으면 앞에 추가
if ! $has_emoji; then
  new_commit_msg="$emoji $new_commit_msg"
fi

if [[ "$prefix_found" != "hotfix" ]]; then

  # 커밋 메시지에 이슈 번호가 이미 있는지 확인
  if [[ "$commit_msg" =~ \#S12P21A106-[0-9]+ ]]; then
    has_issue=true
  else
    has_issue=false
  fi

  # 현재 브랜치 이름 가져오기
  branch_name=$(git symbolic-ref --short HEAD)

  # 브랜치 이름에서 이슈 번호 추출
  issue_number=$(echo "$branch_name" | grep -oE 'S12P21A106-[0-9]+')

  # 메시지에 이슈 번호가 없다면 추가
  if ! $has_issue; then
    new_commit_msg="$new_commit_msg #$issue_number"
  fi
fi

# 커밋 메시지 덮어쓰기
echo "$new_commit_msg" > "$commit_msg_file"
